#!/bin/bash

# Copyright 2021 Hewlett Packard Enterprise Development LP

# Create the Keycloak plugin client configuration.  
# https://github.com/flytreeleft/nexus3-keycloak-plugin
# It is not possible to change the location or format of this
# file without updating the plugin code.  This script needs to
# run when the container is created.

set -e

# The Keycloak realm (typically this will be 'shasta')
KC_REALM=${KC_REALM:-shasta}

# The Keycloak token URL.
if [[ -z "$KC_AUTH_URL" ]]; then
    echo "Must provide KC_AUTH_URL in environment" 1>&2
    exit 1
fi

# The Keycloak client ID.
if [[ -z "$KC_CLIENT_ID" ]]; then
    echo "Must provide KC_CLIENT_ID in environment" 1>&2
    exit 1
fi

# The Keycloak client secret.
if [[ -z "$KC_CLIENT_CRED" ]]; then
    echo "Must provide KC_CLIENT_CRED in environment" 1>&2
    exit 1
fi

# Note the auth server url must only include the
# path to the application and not the full token
# endpoint.  The remainder of the url is constructed
# by the plugin.
cat > /opt/sonatype/nexus/etc/keycloak.json << EOF
{
  "realm": "$KC_REALM",
  "auth-server-url": "$(echo $KC_AUTH_URL | sed 's/keycloak.*/keycloak/')",
  "ssl-required": "external",
  "resource": "$KC_CLIENT_ID",
  "verify-token-audience": true,
  "credentials": {
    "secret": "$KC_CLIENT_CRED"
  },
  "use-resource-role-mappings": true,
  "confidential-port": 0,
  "policy-enforcer": {}
}
EOF
