#!/bin/bash

# Copyright 2021 Hewlett Packard Enterprise Development LP

# Create the Keycloak plugin client configuration.  Note that
# it is not possible to change the location or format of this
# file without updating the plugin code.  This script needs to
# run when the container is created.

set -e
if [[ -z "$KC_AUTH_URL" ]]; then
    echo "Must provide KC_AUTH_URL in environment" 1>&2
    exit 1
fi
if [[ -z "$KC_CLIENT_ID" ]]; then
    echo "Must provide KC_CLIENT_ID in environment" 1>&2
    exit 1
fi
if [[ -z "$KC_CLIENT_CRED" ]]; then
    echo "Must provide KC_CLIENT_CRED in environment" 1>&2
    exit 1
fi


cat > /opt/sonatype/nexus/etc/keycloak.json << EOF
{
  "realm": "shasta",
  "auth-server-url": "$KC_AUTH_URL",
  "ssl-required": "external",
  "resource": "$KC_CLIENT_ID",
  "verify-token-audience": true,
  "credentials": {
    "secret": "$KC_CLIENT_CRED"
  },
  "use-resource-role-mappings": true,
  "confidential-port": 0,
  "policy-enforcer": {}
}
EOF
