#!/bin/bash

# Copyright 2021 Hewlett Packard Enterprise Development LP

# Fetch the plugin and generate the NXRM property file configuration.
# Note that later versions of NXRM only require the .kar file but we
# sync both kar and jar incase it is required.  These are also checked in.

set -e

# See https://github.com/flytreeleft/nexus3-keycloak-plugin
fetch() {
    for ver in "$@"; do
        curl -sfL "https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/v${ver}/nexus3-keycloak-plugin-${ver}.jar" > "nexus3-keycloak-plugin-${ver}.jar"
        curl -sfL "https://github.com/flytreeleft/nexus3-keycloak-plugin/releases/download/v${ver}/nexus3-keycloak-plugin-${ver}-bundle.kar" > "nexus3-keycloak-plugin-${ver}-bundle.kar"
        echo "reference\:file\:/org/github/flytreeleft/nexus3-keycloak-plugin/${ver}/nexus3-keycloak-plugin-${ver}.jar = 200" >> startup.properties
    done
}

fetch 0.5.0
