name: Build nexus3 image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-image.yaml
      - Dockerfile
      - keycloak-plugin/nexus3-keycloak-plugin-0.5.0-bundle.kar
      - keycloak-plugin/generate-credential-config
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref:
          - master
          - 3.25.0
      fail-fast: false
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: cray-hpe/nexus3

      - name: Checkout sonatype/docker-nexus3
        uses: actions/checkout@v2
        with:
          repository: sonatype/docker-nexus3
          path: sonatype/docker-nexus3
          ref: ${{ matrix.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Check cosign install
        run: cosign version

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sonatype/nexus3:${{ matrix.ref }}
        id: build-upstream
        uses: docker/build-push-action@v2
        with:
          context: sonatype/docker-nexus3
          push: true
          tags: |
            localhost:5000/sonatype/nexus3

      - name: Get sonatype/nexus3 release
        id: release
        shell: bash
        env:
          IMAGE: localhost:5000/sonatype/nexus3@${{ steps.build-upstream.outputs.digest }}
        run: echo "::set-output name=release::$(docker image inspect -f '{{ index .Config.Labels "release" }}' "$IMAGE")"

      - name: Build nexus3:${{ steps.release.outputs.release }}
        uses: docker/build-push-action@v2
        with:
          context: cray-hpe/nexus3
          build-args: |
            IMAGE=localhost:5000/sonatype/nexus3@${{ steps.build-upstream.outputs.digest }}
          push: true
          tags: |
            ghcr.io/cray-hpe/nexus3:${{ github.sha }}
            ghcr.io/cray-hpe/nexus3:${{ steps.release.outputs.release }}

      - name: Sign nexus3:${{ steps.release.outputs.release }}
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          IMAGE_TAG: ${{ steps.release.outputs.release }}
        run: |
          cosign sign -key $COSIGN_KEY -a GIT_HASH=$GITHUB_SHA ghcr.io/cray-hpe/nexus3:$GITHUB_SHA
          cosign sign -key $COSIGN_KEY -a GIT_TAG=$IMAGE_TAG ghcr.io/cray-hpe/nexus3:$IMAGE_TAG
