name: Build, sign, and scan image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - release/**
  workflow_dispatch:

#jobs:
#  build:
#    uses: Cray-HPE/.github/.github/workflows/container-image-build.yml@main
#    with:
#      name: nexus3
#      #stable: startsWith(github.ref, 'refs/tags/v')
#      #tags: |-
#      #  type=schedule
#      #  type=ref,event=branch
#      #  type=ref,event=pr
#      #  type=semver,pattern={{version}}
#      #  type=semver,pattern={{major}}.{{minor}}
#      #  type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
#      snyk-args: --file=Dockerfile --severity-threshold=medium
#      upload-scan-results: ${{ github.event_name != 'pull_request' }}
#    secrets:
#      registry-username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
#      registry-password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
#      snyk-token: ${{ secrets.SNYK_TOKEN }}
#    permissions:
#      contents: read
#      id-token: write
#      security-events: write

jobs:
  build:
    name: Build and push image

    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      refs: ${{ steps.build.outputs.refs }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: artifactory.algol60.net/csm-docker
          username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: build
        uses: Cray-HPE/github-actions/container-images/build@main
        with:
          stable-images: artifactory.algol60.net/csm-docker/stable/nexus3
          unstable-images: artifactory.algol60.net/csm-docker/unstable/nexus3

  sign:
    name: Sign image

    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: Cray-HPE/github-actions/setup-cosign@main

      - uses: Cray-HPE/github-actions/setup-gcloud@main
        id: gcloud

      - name: Sign image
        uses: Cray-HPE/github-actions/container-images/sign@main
        with:
          images: ${{ join(fromJSON(needs.build.outputs.refs), '\n') }}
          key: ${{ steps.gcloud.outputs.cosign-build-key }}

  trivy:
    name: Scan image (Trivy)
    #if: ${{ github.event_name == 'pull_request' }}

    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: Cray-HPE/github-actions/container-images/scan/trivy@main
        with:
          image: ${{ fromJSON(needs.build.outputs.refs)[0] }}
          retention-days: ${{ needs.build.outputs.stable == 'true' && 90 || 5 }}
          upload-sarif: ${{ needs.build.outputs.stable == 'true' }}

  snyk:
    name: Scan image (Snyk)

    needs: build
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Snyk scan image for vulnerabilities
        id: scan
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ fromJSON(needs.build.outputs.refs)[0] }}
          json: true
          args: --file=Dockerfile

      - name: Upload results
        if: ${{ hashFiles('snyk.json') != ''}}
        uses: actions/upload-artifact@v2
        with:
          name: snyk-results
          path: |
            snyk.json
          retention-days: ${{ needs.build.outputs.stable == 'true' && 90 || 5 }}

      # Filter for Snyk results for fixable vulnerabilties
      - uses: snyk/actions/setup@master
        if: ${{ needs.build.outputs.stable == 'true' && hashFiles('snyk.json') != ''}}

      - name: Create Snyk policy to ignore unfixable vulnerabilities
        if: ${{ needs.build.outputs.stable == 'true' && hashFiles('snyk.json') != ''}}
        run: |-
          export created="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
          export expires="$(date -u '+%Y-%m-%dT%H:%M:%SZ' -d '90 days')"
          [ -f .snyk ] || yq e -n '{"version": "v1.22.1", "ignore": {}, "patch": {}}' > .snyk
          jq -r '.vulnerabilities[] | select(.isUpgradeable or .isPatchable or .nearestFixedInVersion | not) | .id' snyk.json | while read snykid; do
            export snykid
            yq e -i '.ignore[strenv(snykid)] = [{"*": {"reason": "Not Fixable", "expires": strenv(expires), "created": strenv(created)}}]' .snyk
          done

      - name: Snyk scan image for **fixable** vulnerabilities
        if: ${{ needs.build.outputs.stable == 'true' && hashFiles('snyk.json') != '' }}
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.snyk-token }}
        with:
          image: ${{ fromJSON(needs.build.outputs.refs)[0] }}
          json: false
          # Note: Even with `sarif: true` SARIF output is only generated if `--file=` is specified in args
          sarif: true
          args: --file=Dockerfile --policy-path=.snyk

      - name: Upload fixable vulnerabilities to GitHub Code Scanning
        if: ${{ hashFiles('snyk.sarif') != ''}}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Check if scans found vulnerabilities
        if: ${{ steps.scan.outcome == 'failure' }}
        run: echo "::error::Snyk scan found vulnerabilities"
