name: Build sonatype/nexus3 container image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-image-nexus3.yaml
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v2

      - name: Read version
        id: read_version
        shell: bash
        run: echo "::set-output name=version::$(grep -e '^FROM sonatype/nexus3:' Dockerfile | sed -e 's/^FROM sonatype\/nexus3://g' -e 's/-.*$//')-csm"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cray-hpe/nexus3:latest
            ghcr.io/cray-hpe/nexus3:${{ steps.read_version.outputs.version }}
