name: Build image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-image.yaml
      - Dockerfile
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  registry: artifactory.algol60.net/csm-docker

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref:
          - master
          - 3.25.0
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: cray-hpe/nexus3

      - name: Checkout sonatype/docker-nexus3
        uses: actions/checkout@v2
        with:
          repository: sonatype/docker-nexus3
          path: sonatype/docker-nexus3
          ref: ${{ matrix.ref }}

      - name: Parse Nexus version
        id: parse-version
        shell: bash
        run: echo "::set-output name=version::$(grep -e '^ARG NEXUS_VERSION=' sonatype/docker-nexus3/Dockerfile | sed -e 's/^ARG NEXUS_VERSION=//' -e 's/-.*$//')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Check cosign install
        run: cosign version

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: Login to Artifactory Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}

      - name: Build sonatype/nexus3:${{ steps.parse-version.outputs.version }}
        id: build-base
        uses: docker/build-push-action@v2
        with:
          context: sonatype/docker-nexus3
          push: true
          tags: |
            ${{ env.registry }}/docker.io/sonatype/nexus3:${{ steps.parse-version.outputs.version }}

      - name: Build nexus3:${{ steps.parse-version.outputs.version }}
        id: build-nexus3
        uses: docker/build-push-action@v2
        with:
          context: cray-hpe/nexus3
          build-args: |
            IMAGE=${{ env.registry }}/docker.io/sonatype/nexus3:${{ steps.parse-version.outputs.version }}@${{ steps.build-base.outputs.digest }}
          push: true
          tags: |
            ${{ env.registry }}/nexus3:${{ steps.parse-version.outputs.version }}

      - name: Sign image tags
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          IMAGE: ${{ env.registry }}/nexus3:${{ steps.parse-version.outputs.version }}
        run: cosign sign -key $COSIGN_KEY -a GIT_TAG=$IMAGE_TAG -a GIT_HASH=$GITHUB_SHA $IMAGE

      # TODO: Scan image and save results
