name: Build sonatype/nexus3 container image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-image-nexus3.yaml
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout tools repo
        uses: actions/checkout@v2

      - name: Read version
        id: read_version
        shell: bash
        run: echo "::set-output name=version::$(grep -e '^FROM sonatype/nexus3:' Dockerfile | sed -e 's/^FROM sonatype\/nexus3://g' -e 's/-.*$//')-csm"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.0.0'
      - name: Check cosign install
        run: cosign version

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cray-hpe/nexus3:${{ github.sha }}
            ghcr.io/cray-hpe/nexus3:${{ steps.read_version.outputs.version }}
            ghcr.io/cray-hpe/nexus3:latest

      - name: Sign
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          IMAGE_TAG: ${{ steps.read_version.outputs.version }}
        run: |
          cosign sign -key $COSIGN_KEY -a GIT_HASH=$GITHUB_SHA ghcr.io/cray-hpe/nexus3:$GITHUB_SHA
          cosign sign -key $COSIGN_KEY -a GIT_TAG=$IMAGE_TAG ghcr.io/cray-hpe/nexus3:$IMAGE_TAG
