name: Build image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - release/**
  workflow_dispatch:

jobs:
  build:
    uses: Cray-HPE/.github/.github/workflows/container-image-build.yml@main
    with:
      name: nexus3
      #stable: startsWith(github.ref, 'refs/tags/v')
      #tags: |-
      #  type=schedule
      #  type=ref,event=branch
      #  type=ref,event=pr
      #  type=semver,pattern={{version}}
      #  type=semver,pattern={{major}}.{{minor}}
      #  type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      snyk-args: --severity-threshold=medium
      upload-scan-results: ${{ github.event_name != 'pull_request' }}
    secrets:
      registry-username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}
    permissions:
      contents: read
      id-token: write
      security-events: write
