name: Nightly build, sign, and scan images

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    # Note: on.schedule triggered workflows ALWAYS run on the default branch.
    # This matrixed job checks out specific refs to build, sign, and scan;
    # however, care is taken to make sure individual steps reference the
    # correct Git ref and commit SHA as opposed to what's in the github context
    # (e.g., github.ref and github.sha).

    strategy:
      matrix:
        ref:
          - main
          - v3.25.0-2
    steps:
      - uses: actions/checkout@v2

      - name: Trigger Build (${{ matrix.ref }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ matrix.ref }}
        shell: bash
        run: |
          curl -sfi \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -X POST "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/workflows/build-image.yaml/dispatches" \
            --data "{\"ref\":\"${REF}\"}"

      - name: Build (${{ matrix.ref }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ matrix.ref }}
          DEBUG: 'true'
        run: |
          #gh workflow run build-image.yaml --ref "$REF"
          gh run list --workflow=build-image.yaml
