name: Nightly build, sign, and scan images

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    # Note: on.schedule triggered workflows ALWAYS run on the default branch.
    # This matrixed job checks out specific refs to build, sign, and scan;
    # however, care is taken to make sure individual steps reference the
    # correct Git ref and commit SHA as opposed to what's in the github context
    # (e.g., github.ref and github.sha).

    strategy:
      matrix:
        ref:
          - main
          - v3.25.0-2
    steps:
      - name: Build (${{ matrix.ref }})
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          REF: ${{ matrix.ref }}
        run: gh workflow run build-image.yaml --ref "$REF"
