name: Nightly build, sign, and scan images

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    # Note: on.schedule triggered workflows ALWAYS run on the default branch.
    # This matrixed job checks out specific refs to build, sign, and scan;
    # however, care is taken to make sure individual steps reference the
    # correct Git ref and commit SHA as opposed to what's in the github context
    # (e.g., github.ref and github.sha).

    strategy:
      matrix:
        ref:
          - main
          - v3.25.0-2
          - v3.38.0

    steps:
      - name: Get auth token
        uses: navikt/github-app-token-generator@v1
        id: gen-token
        with:
          private-key: ${{ secrets.ALGOL60_GITHUB_READONLY_APP }}
          app-id: 129003

      - name: Build (${{ matrix.ref }})
        env:
          GITHUB_TOKEN: ${{ steps.gen-token.outputs.token }}
          GH_REPO: ${{ github.repository }}
          REF: ${{ matrix.ref }}
          DEBUG: 'true'
        run: |
          gh workflow run build-image.yaml --ref "$REF"
          gh run list --workflow=build-image.yaml
