name: Sign nexus3 image

on:
  workflow_dispatch: {}

jobs:
  sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: artifactory.algol60.net/csm-docker
          username: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}

      - uses: Cray-HPE/github-actions/setup-cosign@main

      - uses: Cray-HPE/github-actions/setup-gcloud@main
        id: gcloud

      - name: Sign image
        uses: Cray-HPE/github-actions/cosign@main
        with:
          images: artifactory.algol60.net/csm-docker/stable/nexus3:3.25.0-2
          key: ${{ steps.gcloud.outputs.cosign-build-key }}

